function repa_dependency_version_error(depLabel, foundVersion, requiredVersion)
error(sprintf(['Pinned %s version mismatch.\n', ...
    'Found: %s\n', ...
    'Required: %s\n\n', ...
    'Place the pinned release in REPA/third_party/ or run scripts/prepare_offline_bundle.m.'], ...
    depLabel, foundVersion, requiredVersion));
end
